### PR TITLE
Added system instruction support.

### PR DESCRIPTION
**Pull request by kddlb**
I'm not sure if it's up to Google's coding standards.

### CODE REVIEW

**Comment by devoncarew** [comment]
Interesting; I found some docs for this feature here: https://ai.google.dev/docs/system_instructions. Do you have any links to API docs for how this is exposed in other sdks (Python, REST, ...)?

**Comment by devoncarew** [comment]
cc @natebosch

**Comment by kddlb** [comment]
I looked at the Python version of the SDK. https://github.com/googleapis/google-cloud-python/blob/d9222a97786ce1badae4561410ca5e09386a3377/packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta/types/generative_service.py#L144

**Comment by natebosch** [comment]
Thanks for the PR!

There were a few changes we would have needed to make here, but I had a local branch with those changes almost all ready so I went ahead and pushed up that PR to shorten the cycle time. Primarily my version accepts `Content?` instead of `String?` to match the backend API a little more directly. In the Python SDK I think they tend to be a little looser with types and accept multiple formats. If we had union types or method overloads I'd probably do the same and accept either `String` or `Content`.

I'll close this PR for now and run with #119

**Pull request closed without merging**
